name: <WORKFLOW_NAME>
on: create

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.REPO_ACCESS_TOKEN }}
          approvers: makervinod,vinodm97
          minimum-approvals: 1
          issue-title: "Deploying Dev"
          issue-body: "Please approve or deny the deployment of Dev"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ""
          additional-denied-words: ""

      - name: Run Python Applications
        run: python main.py
